version: '3.8'
services:
    database:
        image: mysql:latest
        env_file: 
            - path: ./.env
              required: true
        environment:
            - MYSQL_DATABASE=database
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

        volumes:
            - db-data:/var/lib/mysqld
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 3307:3306
        networks:
            - private
        restart: unless-stopped

    server:
        depends_on:
            - database
        build: ./server
        env_file: 
            - path: ./.env
              required: true
        ports:
            - 53342:53342
        networks:
            - public
            - private
        restart: unless-stopped
    client:
        depends_on:
            - server
        build: ./client
        ports:
            - 80:42067
        networks:
            - public
        restart: unless-stopped


volumes: 
    db-data:
networks:
    public:
    private:
