version: '3.8'
services:
    database:
        image: mysql:latest
        env_file: 
            - path: ./.env
              required: true
        environment:
            - MYSQL_DATABASE=database
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

        volumes:
            - db-data:/var/lib/mysqld
            - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - private
        restart: unless-stopped

    server:
        depends_on:
            - database
        build: ./server
        env_file: 
            - path: ./.env
              required: true
        environment:
            - DB_DATABASE=database
            - DB_USERNAME=root
            - DB_PASSWORD=${DB_ROOT_PASSWORD}
            - DB_HOST=database
        ports:
            - ${SERVER_DOCKER_PORT}:${SERVER_LOCAL_PORT}
        networks:
            - public
            - private
        restart: unless-stopped
    client:
        env_file: 
            - path: ./.env
              required: true
        depends_on:
            - server
        build: ./client
        ports:
            - ${CLIENT_DOCKER_PORT}:${CLIENT_LOCAL_PORT}
        networks:
            - public
        restart: unless-stopped


volumes: 
    db-data:
networks:
    public:
    private:
